export const appArtwork = {
  appIcon: require('../../assets/images/icon.png'),
  borrowSuccess: require('../../assets/illustrations/borrow-success.png'),
  borrowingEmpty: require('../../assets/illustrations/borrowing-empty.png'),
  interestSelection: require('../../assets/illustrations/interest-selection.png'),
  loginWelcome: require('../../assets/illustrations/login-welcome.png'),
  noResults: require('../../assets/illustrations/no-results.png'),
  notionBorrowSuccess: require('../../assets/illustrations/notion-style/borrow-success-alpha.png'),
  notionBooklistEmpty: require('../../assets/illustrations/notion-style/ChatGPT Image Apr 2, 2026, 05_38_10 PM.png'),
  notionEmptyCollection: require('../../assets/illustrations/notion-style/ChatGPT Image Apr 2, 2026, 05_33_00 PM.png'),
  notionEmptySearchCollection: require('../../assets/illustrations/notion-style/ChatGPT Image Apr 2, 2026, 05_36_20 PM.png'),
  notionFirstEntry: require('../../assets/illustrations/notion-style/first-entry-alpha.png'),
  notionInterestSelection: require('../../assets/illustrations/notion-style/interest-selection-alpha.png'),
  notionInterestSelectionFocused: require('../../assets/illustrations/notion-style/ChatGPT Image Apr 2, 2026, 05_32_14 PM.png'),
  notionNoResults: require('../../assets/illustrations/notion-style/no-results-alpha.png'),
  notionRegisterWelcome: require('../../assets/illustrations/notion-style/ChatGPT Image Apr 2, 2026, 05_42_38 PM.png'),
  notionReadingProgress: require('../../assets/illustrations/notion-style/reading-in-progress-alpha.png'),
  notionReturnSuccess: require('../../assets/illustrations/notion-style/ChatGPT Image Apr 2, 2026, 05_42_49 PM.png'),
  profileHero: require('../../assets/illustrations/interest-selection.png'),
  recommendationHero: require('../../assets/illustrations/recommendation-hero.png'),
  returnSuccess: require('../../assets/illustrations/return-success.png'),
  robotDelivery: require('../../assets/illustrations/robot-delivery.png'),
} as const;
